services:
  postgres:
    image: ankane/pgvector
    container_name: chatbot_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chatbotdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: chatbot_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  n8n:
    image: n8nio/n8n
    container_name: chatbot_n8n
    restart: always
    environment:
      - GENERIC_TIMEZONE=America/Los_Angeles
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

  chatbot:
    build: ./chatbot
    container_name: chatbot_node
    restart: no
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: postgres://admin:admin@postgres:5432/chatbotdb
    ports:
      - "3000:3000"
    depends_on:
      - postgres


volumes:
  postgres_data:
  n8n_data:
